apiVersion: v1
kind: Service
metadata:
  name: python-web-app-service
spec:
  type: LoadBalancer
  selector:
    app: python-web
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: kotlin-native-web-app-service
spec:
  type: LoadBalancer
  selector:
    app: kotlin-native-web
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

